### ISSUE TITLE
Is this dashboard functional?

### ISSUE THREAD

**Issue by akoranne** [splunk/splunk-addon-for-cloud-foundry#1]
Is this dashboard functional? 
Under the `bin` folder, I see no executables. 

Can you please confirm if dashboard version is functional? If not, do I take another branch?
Please let me know.

**Comment by rarsan** [comment]
Hi @akoranne,
As mentioned in README, a prerequisite for this Add-on is the [Splunk Firehose Nozzle](https://github.com/cloudfoundry-community/splunk-firehose-nozzle) which collects data from Cloud Foundry Firehose and forwards it to a Splunk deployment. This Add-on only provides necessary searches to analyze the data, in addition to a sample dashboard, and several UI prebuilt panels.
